import datetime
import json
import urllib.request
import urllib.error

class AlertDispatcher:
    """
    Handles routing alerts generated by use cases to the local database
    and syncing them to the central HQ via the FastAPI backend.
    """
    def __init__(self, site_id: str, api_url: str = "https://central-hub-tih5.onrender.com"):
        self.site_id = site_id
        self.api_url = api_url
        
    def dispatch(self, camera_id: str, usecase: str, alert_data: dict):
        payload = {
            "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
            "site_id": self.site_id,
            "camera_id": camera_id,
            "usecase": usecase,
            "alert_type": alert_data.get("type", "unknown"),
            "severity": alert_data.get("severity", "medium"),
            "description": alert_data.get("description", ""),
            "bbox": alert_data.get("bbox", [])
        }
        
        # Send to local FastAPI backend
        try:
            req = urllib.request.Request(
                f"{self.api_url}/alerts/",
                data=json.dumps(payload).encode('utf-8'),
                headers={'Content-Type': 'application/json'},
                method='POST'
            )
            with urllib.request.urlopen(req) as response:
                if response.status == 200:
                    print(f"[ALERT DISPATCHED] -> Backend: {alert_data.get('type')}")
        except Exception as e:
            print(f"[DISPATCH ERROR] Failed to send alert: {e}")
            
        return True
