import datetime
import json
import urllib.request
import urllib.error
import sqlite3
import threading
import time

class AlertDispatcher:
    """
    Handles routing alerts generated by use cases.
    Saves them to a local SQLite queue and attempts to sync them to the central HQ.
    """
    def __init__(self, site_id: str, api_url: str = "https://central-hub-tih5.onrender.com"):
        self.site_id = site_id
        self.api_url = api_url
        self.db_path = "local_alert_queue.db"
        self._init_db()
        
        # Start background sync worker
        self.sync_thread = threading.Thread(target=self._sync_worker, daemon=True)
        self.sync_thread.start()

    def _init_db(self):
        with sqlite3.connect(self.db_path) as conn:
            conn.execute('''
                CREATE TABLE IF NOT EXISTS alert_queue (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    payload TEXT NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
            ''')

    def dispatch(self, camera_id: str, usecase: str, alert_data: dict):
        payload = {
            "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
            "site_id": self.site_id,
            "camera_id": camera_id,
            "usecase": usecase,
            "alert_type": alert_data.get("type", "unknown"),
            "severity": alert_data.get("severity", "medium"),
            "description": alert_data.get("description", ""),
            "bbox": alert_data.get("bbox", [])
        }
        
        # Save to local queue instantly (Offline Resilience)
        with sqlite3.connect(self.db_path) as conn:
            conn.execute("INSERT INTO alert_queue (payload) VALUES (?)", (json.dumps(payload),))
        print(f"[QUEUED] Alert saved locally for {usecase}")
        return True

    def _sync_worker(self):
        """Background thread that constantly tries to push queued alerts to the cloud."""
        while True:
            try:
                with sqlite3.connect(self.db_path) as conn:
                    cursor = conn.cursor()
                    cursor.execute("SELECT id, payload FROM alert_queue ORDER BY id ASC LIMIT 50")
                    rows = cursor.fetchall()
                    
                if not rows:
                    time.sleep(2)
                    continue

                for row_id, payload_str in rows:
                    req = urllib.request.Request(
                        f"{self.api_url}/alerts/",
                        data=payload_str.encode('utf-8'),
                        headers={'Content-Type': 'application/json'},
                        method='POST'
                    )
                    with urllib.request.urlopen(req, timeout=5) as response:
                        if response.status == 200:
                            with sqlite3.connect(self.db_path) as conn:
                                conn.execute("DELETE FROM alert_queue WHERE id = ?", (row_id,))
                            print(f"[SYNCED] Alert {row_id} pushed to Central HQ")
            except Exception as e:
                # Network down, sleep and retry later
                time.sleep(5)
