@echo off
echo Starting Central Hub Platform...

echo 1. Starting FastAPI Backend...
start cmd /k "cd backend_api && pip install -r requirements.txt 2>nul || echo. && uvicorn main:app --reload --port 8000"

echo 2. Starting React Dashboard...
start cmd /k "npm install && npm run dev"

echo 3. Starting Camera Agent (AI Pipeline)...
echo Waiting 5 seconds for backend to initialize...
timeout /t 5
start cmd /k "cd camera_agent && pip install -r requirements.txt 2>nul || echo. && python core/agent.py"

echo All services launched!
